# Generated by Django 3.2.7 on 2022-04-20 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ratio',
        ),
    ]
