# Generated by Django 3.2.7 on 2022-04-20 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_userprofile_hascookies'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userprofile',
            table='person',
        ),
    ]
