# Generated by Django 3.2.7 on 2022-04-27 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_userprofile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(default='images/Users/1.png', null=True, upload_to='images/Users'),
        ),
    ]
