# Generated by Django 3.2.7 on 2022-02-21 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Title')),
                ('announce', models.CharField(max_length=200, verbose_name='Announce')),
                ('full_text', models.TextField(verbose_name='Full_text')),
                ('date', models.DateTimeField(verbose_name='Date')),
                ('language', models.CharField(max_length=30, verbose_name='Language')),
                ('author', models.CharField(max_length=125, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
            },
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=0, verbose_name='Rating')),
                ('post', models.CharField(max_length=100, verbose_name='Post')),
                ('user', models.CharField(max_length=50, verbose_name='User')),
                ('language', models.CharField(max_length=30, verbose_name='Language')),
                ('text', models.TextField(max_length=400, verbose_name='Text')),
                ('date', models.DateTimeField(verbose_name='Date')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
            },
        ),
        migrations.CreateModel(
            name='Discuss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Title')),
                ('question', models.CharField(max_length=200, unique=True, verbose_name='Question')),
                ('date', models.DateTimeField(verbose_name='Date')),
                ('author', models.CharField(max_length=50, verbose_name='User')),
                ('language', models.CharField(max_length=30, verbose_name='Language')),
            ],
            options={
                'verbose_name': 'Discussion',
                'verbose_name_plural': 'Discussion',
            },
        ),
    ]
