# Generated by Django 3.2.7 on 2022-04-27 20:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('languages', '0002_article_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='dislikes',
            field=models.ManyToManyField(related_name='dislikes_articles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='discuss',
            name='dislikes',
            field=models.ManyToManyField(related_name='dislikes_discuss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='discuss',
            name='likes',
            field=models.ManyToManyField(related_name='likes_discuss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='article',
            name='likes',
            field=models.ManyToManyField(related_name='likes_articles', to=settings.AUTH_USER_MODEL),
        ),
    ]
