# Generated by Django 3.2.7 on 2022-05-06 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0003_auto_20220427_2309'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
    ]
