# Generated by Django 3.2.7 on 2022-05-06 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0004_comments_is_correct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='post',
            field=models.IntegerField(verbose_name='Post'),
        ),
    ]
